//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Montadora
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_series
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_series()
        {
            this.tbl_carros = new HashSet<tbl_carros>();
        }
    
        public byte id { get; set; }
        public string serienum { get; set; }
        public byte tipo_carroceria { get; set; }
        public string chassis { get; set; }
    
        public virtual tbl_carroceria tbl_carroceria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_carros> tbl_carros { get; set; }
    }
}
